include:
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.94/workflow-default.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.94/terraform-toolkit.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.94/git-toolkit.yml'
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.94/gitlab-toolkit.yml"

get-latest-terraform:
  extends: .get-latest-terraform

unit-tests:
  image: python:3.9-buster
  script:
    - pip install coverage==6.0.1 unittest-xml-reporting==3.0.4
    - cd auto_verifier_lambda
    - coverage run -m xmlrunner --output-file report.xml
    - coverage report
    - coverage xml
  tags:
    - miquido
    - docker
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    reports:
      junit: auto_verifier_lambda/report.xml
      cobertura: auto_verifier_lambda/coverage.xml

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate-terraform
  variables:
    ENVIRONMENTS: examples/complete

miquido-ci-schema-validation:
  extends: .miquido-ci-schema-validation

bump-tag:
  extends: .bump_minor_tag

docs:
  extends: .generate_readme
  stage: .post

push_readme:
  extends: .push_readme
  stage: .post
  dependencies: ["docs"]
  needs: ["docs"]
