include:
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.12/workflow-default.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.12/terraform-toolkit.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.12/git-toolkit.yml'

get-latest-terraform:
  extends: .get-latest-terraform

unit-tests:

  image: python:3.9-buster
  script:
    - cd auto_verifier_lambda
    - python -m unittest discover tests
  tags:
    - miquido
    - docker

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate
  variables:
    ENVIRONMENTS: examples/complete

bump-tag:
  extends: .bump_minor_tag
